<h1>NN Layers</h1>
* TF Keras

Hier sollen verschiedenen Layers näher untersucht werden. 

> Alle TF Keras Layers: <br>
> https://www.tensorflow.org/api_docs/python/tf/keras/layers [Letzter Zugriff: 17.09.2024]

Es gibt sehr viele verschiedene Layers die verschiedenste Aufgaben übernehmen.

In [1]:
# Imports
import tensorflow as tf
import numpy as np

<h2>Input Layer</h2>

Als Layer `tf.keras.layers.InputLayer` oder Funktion `tf.keras.layers.Input()`.

In [2]:
# Instanziiere ein Keras Tensor mit einer bestimmten Form. 
# - Gebe Form der Daten an. 
shape_tuple = (5, 5)

input_layer = tf.keras.layers.Input(shape=shape_tuple)

Wichtige Parameter: <br>
- <b>shape</b>: Form des Tensors, z. B. 2-D (5, 5)
- <b>batch_size</b>: Optionale Batchgröße
- <b>name</b>: Optionaler Name
- <b>dtype</b>: Erwarteter Datentyp as String "float32", ...
- <b>sparse</b>: True/False: Wenn ein Tensor viele Nullen enthält, werden nur die <u>nicht</u>-Nullen gespeichert, das spart Speicherplatz. <br> Default ist False: speichere alles, True meist für NLP Aufgaben wo es viele Nullen gibt (bag-of-words, ...)
- <b>tensor</b>: Nutze einen bereits existierenden Tensor als Input. <br>
tf.constant([[1.0, 2.0], [3.0, 4.0]]) => shape(2, 2) => tf.keras.layers.Input(tensor=existing_tensor)


In [203]:
input_layer.shape

(None, 5, 5)

Mit der Funktion `tf.expand_dims()` kann die Dimension verändert werden.
- `tf.expand_dims(data, axis=0)`: Batch Dimension.  (2, 3) => (1, 2, 3)
- `tf.expand_dims(data, axis=-1)`: Channel Dimension, wenn es Bilddaten sind. (2, 3) => (2, 3, 1)

<h3>1-D</h3>

Tensorflow fügt immer eine Batchdimension `None` ein, die ein dynamischen Input nehmen kann.

<b>*</b>Es muss ggf. neben dem Input ein weiterer Layer hinzugefügt werden, sonst setze zu Beginn Batchsize. 

In [8]:
# 1-D #  Beispiel 1
# - [1,2,3, ...]
input_layer = tf.keras.layers.Input(shape=(2,), dtype="int16")
print(input_layer)
model       = tf.keras.Sequential([input_layer])
# Output soll linear sein. 
# - Ohne layer -> Error -> setze dann zu Beginn feste Batchgröße 
model.add(tf.keras.layers.Dense(2, activation="linear", use_bias=False, kernel_initializer="ones"))

<KerasTensor shape=(None, 2), dtype=int16, sparse=None, name=keras_tensor_3>


In [9]:
my_data = tf.convert_to_tensor([1, 1], dtype=tf.int16)
my_data

<tf.Tensor: shape=(2,), dtype=int16, numpy=array([1, 1], dtype=int16)>

In [10]:
my_data = tf.expand_dims(my_data, axis=0) # Batch-Dimension
model( my_data ) 

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[2., 2.]], dtype=float32)>

In [11]:
# Oder so.:
# - Zusätzlich [] als Dimension 
my_data = tf.convert_to_tensor([[1, 1]], dtype=tf.int16)
model( my_data ) 

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[2., 2.]], dtype=float32)>

In [16]:
# 1-D #  Beispiel 2
input_layer = tf.keras.layers.Input(shape=(10,), dtype="int32", name="Input_Layer_1")
print(input_layer)
model       = tf.keras.Sequential([input_layer])
# Output soll linear sein. 
# - Ohne layer -> Error -> setze dann zu Beginn feste Batchgröße 
model.add(tf.keras.layers.Dense(10, activation="linear", use_bias=False, kernel_initializer="ones", ))

<KerasTensor shape=(None, 10), dtype=int32, sparse=None, name=Input_Layer_1>


In [17]:
my_data = tf.convert_to_tensor([1, 1, 2, 2, 3, 3, 4, 4, 5, 5], dtype=tf.int32)
my_data

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([1, 1, 2, 2, 3, 3, 4, 4, 5, 5])>

In [18]:
my_data = tf.expand_dims(my_data, axis=0)  # Batch-Dimension 
model( my_data )

<tf.Tensor: shape=(1, 10), dtype=float32, numpy=array([[30., 30., 30., 30., 30., 30., 30., 30., 30., 30.]], dtype=float32)>

In [15]:
np.sum(my_data)  # Da jedes Neuron eine Summe berechnet.

30

In [19]:
my_data = tf.convert_to_tensor( [ [1, 1, 2, 2, 3, 3, 4, 4, 5, 5] ] , dtype=tf.int32)
model( my_data )

<tf.Tensor: shape=(1, 10), dtype=float32, numpy=array([[30., 30., 30., 30., 30., 30., 30., 30., 30., 30.]], dtype=float32)>

In [20]:
# Mehrere #
model( tf.reshape([my_data, my_data, my_data], shape=(3, 10)) )

<tf.Tensor: shape=(3, 10), dtype=float32, numpy=
array([[30., 30., 30., 30., 30., 30., 30., 30., 30., 30.],
       [30., 30., 30., 30., 30., 30., 30., 30., 30., 30.],
       [30., 30., 30., 30., 30., 30., 30., 30., 30., 30.]], dtype=float32)>

In [21]:
# 1-D #  Beispiel 3 # Gegebene Batchgröße
input_layer = tf.keras.layers.Input(shape=(10,), dtype="int32", name="Input_Layer_1", batch_size=3)
# - Andere Batchgrößen als Input nach der Definition möglich. 
print(input_layer)
model       = tf.keras.Sequential([input_layer])
# Output soll linear sein. 
# - Ohne layer -> Error -> setze dann zu Beginn feste Batchgröße 
model.add(tf.keras.layers.Dense(10, activation="linear", use_bias=False, kernel_initializer="ones", ))

<KerasTensor shape=(3, 10), dtype=int32, sparse=None, name=Input_Layer_1>


In [22]:
my_data = tf.convert_to_tensor([[1,1,1,1,1,1,1,1,1,1], [1,1,1,1,1,1,1,1,1,1], [1,1,1,1,1,1,1,1,1,1]], dtype=tf.int32) 
my_data

<tf.Tensor: shape=(3, 10), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])>

In [23]:
model( my_data )

<tf.Tensor: shape=(3, 10), dtype=float32, numpy=
array([[10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.]], dtype=float32)>

In [24]:
# Andere Batchsize: 
my_data = tf.convert_to_tensor([[1,1,1,1,1,1,1,1,1,1], [1,1,1,1,1,1,1,1,1,1]], dtype=tf.int32) 
print("data: ", my_data)
model( my_data )

data:  tf.Tensor(
[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]], shape=(2, 10), dtype=int32)


<tf.Tensor: shape=(2, 10), dtype=float32, numpy=
array([[10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.]], dtype=float32)>

<h3>2-D</h3>

Dasselbe Spiel geht auch mit höheren Dimensionen.
- Hier können Generatoren genutzt werden, um Daten zu erzeugen.

In [215]:
np.random.randint(0, 5, (2,2))

array([[2, 0],
       [0, 3]])

In [164]:
# Batch Norm

In [165]:
# Dense