<h1>NN Layers</h1>
* TF Keras

Hier sollen verschiedenen Layers näher untersucht werden. 

> Alle TF Keras Layers: <br>
> https://www.tensorflow.org/api_docs/python/tf/keras/layers [Letzter Zugriff: 17.09.2024]

Es gibt sehr viele verschiedene Layers die verschiedenste Aufgaben übernehmen.

In [2]:
# Imports
import tensorflow as tf

<h2>Input Layer</h2>

Als Layer `tf.keras.layers.InputLayer` oder Funktion `tf.keras.layers.Input()`.

In [109]:
# Instanziiere ein Keras Tensor mit einer bestimmten Form. 
# - Gebe Form der Daten an. 
shape_tuple = (5, 5)

input_layer = tf.keras.layers.Input(shape=shape_tuple)

Parameter: <br>
- <b>shape</b>: Form des Tensors, z. B. 2-D (5, 5)
- <b>batch_size</b>: Optionale Batchgröße
- <b>name</b>: Optionaler Name
- <b>dtype</b>: Erwarteter Datentyp as String "float32", ...
- <b>sparse</b>: True/False: Wenn ein Tensor viele Nullen enthält, werden nur die <u>nicht</u>-Nullen gespeichert, das spart Speicherplatz. <br> Default ist False: speichere alles, True meist für NLP Aufgaben wo es viele Nullen gibt (bag-of-words, ...)
- <b>tensor</b>: Nutze einen bereits existierenden Tensor als Input. <br>
tf.constant([[1.0, 2.0], [3.0, 4.0]]) => shape(2, 2) => tf.keras.layers.Input(tensor=existing_tensor)


In [9]:
input_layer.shape

(None, 5, 5)

In [17]:
# Siehe Meldung # 
input_layer = tf.keras.layers.Input(shape=(2, 5), dtype="int16")
model       = tf.keras.Sequential([input_layer])
model(tf.constant([[1,1,1,1,1], [1,1,1,1,1]]))

# Shape: (None, 2, 5) => TensorFlow Fügt automatisch Batchdimension ein. None-> Größe kann variieren. 
# - (Batchsize, 2, 5) 

ValueError: Sequential model 'sequential_5' has already been configured to use input shape (None, 2, 5). You cannot build it with input_shape (2, 5)

In [22]:
# Möglichkeit 1 # 
input_layer = tf.keras.layers.Input(shape=(2, 5), dtype="int16", batch_size=1)
model       = tf.keras.Sequential([input_layer])
model(tf.constant([ [[1,1,1,1,1], [1,1,1,1,1]] ]))


<tf.Tensor: shape=(1, 2, 5), dtype=int16, numpy=
array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]], dtype=int16)>

In [51]:
# Möglichkeit 2 # 
# - Füge Dimension ein.
# - Mit Numpy, TF, ...

input_layer = tf.keras.layers.Input(shape=(2, 5,), dtype="int32")
model       = tf.keras.Sequential([input_layer])

data = tf.constant([[1,1,1,1,1], [1,1,1,1,1]],  dtype=tf.int32)  # shape (2, 5)

# Siehe tf.expand_dims()
#data = tf.expand_dims(data, axis=0)  # Shape = (1, 2, 5), füge Batchdim. ein.
# data = tf.expand_dims(data, axis=-1)  # Shape = (2, 5, 1), füge Channel ein, z. B. bei Bilddaten die nur (a, b) sind.

In [52]:
data

<tf.Tensor: shape=(2, 5), dtype=int32, numpy=
array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])>

In [45]:
data = data[tf.newaxis, ...]
data

<tf.Tensor: shape=(1, 2, 5), dtype=int32, numpy=
array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])>

In [46]:
input_layer.shape

(None, 2, 5)

In [58]:
tf.convert_to_tensor([ [[1,1,1,1,1],[1,1,1,1,1]] ])

<tf.Tensor: shape=(1, 2, 5), dtype=int32, numpy=
array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])>

In [62]:
test_data = tf.convert_to_tensor([ [[1,1,1,1,1],[1,1,1,1,1]] ])
model(test_data[0])

UnboundLocalError: Exception encountered when calling Sequential.call().

local variable 'outputs' referenced before assignment

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=(2, 5), dtype=int32)
  • training=None
  • mask=None

In [98]:
del model

In [99]:
input_layer = tf.keras.layers.Input(shape=(2, 2,), dtype="int32")
model       = tf.keras.Sequential([input_layer])


In [100]:
test_data = tf.convert_to_tensor([[1,1], [2,2]], dtype=tf.int16)

In [101]:
test_data.shape

TensorShape([2, 2])

In [102]:
input_layer

<KerasTensor shape=(None, 2, 2), dtype=int32, sparse=None, name=keras_tensor_23>

In [108]:
model(test_data)


ValueError: Sequential model 'sequential_22' has already been configured to use input shape (None, 2, 2). You cannot build it with input_shape (2, 2)

In [ ]:
# Batch Norm

In [ ]:
# Dense